require 'test/unit'
require_relative './unit_tests/base_test.rb'
require_relative './unit_tests/help_printer_test.rb'
require_relative './unit_tests/validators/size_validator_test.rb'
require_relative './unit_tests/math_operations/prime_generator_test.rb'
require_relative './unit_tests/math_operations/table_generator_test.rb'
require_relative './unit_tests/formatters/default_formatter_test.rb'
require_relative './unit_tests/formatters/table_formatter_test.rb'
